// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type DeadLetterTask struct {
	ID             string
	OriginalTaskID string
	SubscriptionID string
	Payload        string
	FailedAt       time.Time
	Reason         string
	LastAttemptAt  sql.NullTime
	AttemptCount   int64
	Status         string
	TargetUrl      sql.NullString
	EventType      sql.NullString
	ErrorDetails   sql.NullString
}

type DeliveryLog struct {
	ID             string
	DeliveryTaskID string
	SubscriptionID string
	TargetUrl      string
	Timestamp      time.Time
	AttemptNumber  int64
	Outcome        string
	HttpStatus     sql.NullInt64
	ErrorDetails   sql.NullString
}

type DeliveryTask struct {
	ID             string
	SubscriptionID string
	Payload        string
	CreatedAt      time.Time
	Status         string
	LastAttemptAt  sql.NullTime
	AttemptCount   int64
}

type Subscription struct {
	ID         string
	TargetUrl  string
	Secret     sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
	EventTypes sql.NullString
}
