services:
  app:
    build: .
    container_name: webhook-app
    ports:
      - "8080:8080"
    env_file:
      - .env # .env can override REDIS_URL if you want to use an external Redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: webhook-redis
    ports:
      - "6379:6379" 
    restart: unless-stopped
    volumes:
      - redis_data:/data 

volumes:
  redis_data: 